apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-sample-project
  namespace: kargo-sample-project
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true