
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: kargo-sample-project 
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/Gkemhcs/kargo-sample-demo.git
  username: gkemhcs-bot 
  password:  PASSWORD 
