apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-sample-warehouse
  namespace: kargo-sample-project
spec:
  subscriptions:
  - image: 
      repoURL: docker.io/gkemhcs/kargo-sample-demo
      imageSelectionStrategy: NewestBuild
